#OS config
dist: trusty
sudo: false
before_install:
  - gem install bundler
  - gem update bundler

#Language config
language: ruby
rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  
after_success:
  - bash <(curl -s https://codecov.io/bash)

#Notifications config
notifications:
  email: false
